services:
  - type: web
    name: crudbasico-frontend
    runtime: static
    buildCommand: pnpm install --frozen-lockfile && pnpm build
    staticPublishPath: ./frontend/out
    envVars:
      - key: NODE_VERSION
        value: 22
