@baseUrl = http://localhost:3001

### Status da API
GET {{baseUrl}}/health

### Criar usuario
POST {{baseUrl}}/usuarios
Content-Type: application/json

{
  "nome": "Ismael Brandao",
  "email": "ismael@example.com",
  "senha": "123456"
}

### Listar usuarios
GET {{baseUrl}}/usuarios

### Buscar usuario por ID
GET {{baseUrl}}/usuarios/1

### Atualizar usuario
PUT {{baseUrl}}/usuarios/1
Content-Type: application/json

{
  "nome": "Ismael Brandao",
  "email": "ismael.brandao@example.com",
  "senha": "123456"
}

### Criar produto
POST {{baseUrl}}/produtos
Content-Type: application/json

{
  "nome": "Teclado mecanico",
  "preco": 199.9,
  "estoque": 10
}

### Listar produtos
GET {{baseUrl}}/produtos

### Buscar produto por ID
GET {{baseUrl}}/produtos/1

### Atualizar produto
PUT {{baseUrl}}/produtos/1
Content-Type: application/json

{
  "nome": "Teclado mecanico RGB",
  "preco": 229.9,
  "estoque": 10
}

### Criar pedido
POST {{baseUrl}}/pedidos
Content-Type: application/json

{
  "usuario_id": 1,
  "produto_id": 1,
  "quantidade": 2
}

### Listar pedidos
GET {{baseUrl}}/pedidos

### Buscar pedido por ID
GET {{baseUrl}}/pedidos/1

### Atualizar pedido
PUT {{baseUrl}}/pedidos/1
Content-Type: application/json

{
  "usuario_id": 1,
  "produto_id": 1,
  "quantidade": 1
}

### Deletar pedido
DELETE {{baseUrl}}/pedidos/1

### Deletar produto
DELETE {{baseUrl}}/produtos/1

### Deletar usuario
DELETE {{baseUrl}}/usuarios/1
